# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_form.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1098, 934)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.geometryTab = QtWidgets.QWidget()
        self.geometryTab.setObjectName("geometryTab")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.geometryTab)
        self.gridLayout_13.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.geometryVerticalLayout = QtWidgets.QVBoxLayout()
        self.geometryVerticalLayout.setObjectName("geometryVerticalLayout")
        self.ppRichTextLabel = QtWidgets.QLabel(self.geometryTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ppRichTextLabel.sizePolicy().hasHeightForWidth())
        self.ppRichTextLabel.setSizePolicy(sizePolicy)
        self.ppRichTextLabel.setText("")
        self.ppRichTextLabel.setTextFormat(QtCore.Qt.RichText)
        self.ppRichTextLabel.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.ppRichTextLabel.setObjectName("ppRichTextLabel")
        self.geometryVerticalLayout.addWidget(self.ppRichTextLabel)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.geometryVerticalLayout.addLayout(self.verticalLayout_4)
        self.gridLayout_13.addLayout(self.geometryVerticalLayout, 0, 0, 1, 1)
        self.tabWidget.addTab(self.geometryTab, "")
        self.statisticsTab = QtWidgets.QWidget()
        self.statisticsTab.setObjectName("statisticsTab")
        self.gridLayout_17 = QtWidgets.QGridLayout(self.statisticsTab)
        self.gridLayout_17.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_17.setObjectName("gridLayout_17")
        self.statisticsVerticalLayout = QtWidgets.QVBoxLayout()
        self.statisticsVerticalLayout.setObjectName("statisticsVerticalLayout")
        self.gridLayout_17.addLayout(self.statisticsVerticalLayout, 0, 0, 1, 1)
        self.tabWidget.addTab(self.statisticsTab, "")
        self.pathprofileTab = QtWidgets.QWidget()
        self.pathprofileTab.setObjectName("pathprofileTab")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.pathprofileTab)
        self.gridLayout_9.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.pathprofVerticalLayout = QtWidgets.QVBoxLayout()
        self.pathprofVerticalLayout.setObjectName("pathprofVerticalLayout")
        self.gridLayout_9.addLayout(self.pathprofVerticalLayout, 0, 0, 1, 1)
        self.tabWidget.addTab(self.pathprofileTab, "")
        self.mapTab = QtWidgets.QWidget()
        self.mapTab.setObjectName("mapTab")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.mapTab)
        self.gridLayout_10.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.mapVerticalLayout = QtWidgets.QVBoxLayout()
        self.mapVerticalLayout.setObjectName("mapVerticalLayout")
        self.gridLayout_10.addLayout(self.mapVerticalLayout, 0, 0, 1, 1)
        self.tabWidget.addTab(self.mapTab, "")
        self.gridLayout_8.addWidget(self.tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1098, 20))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.parametersDockWidget = QtWidgets.QDockWidget(MainWindow)
        self.parametersDockWidget.setObjectName("parametersDockWidget")
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.gridLayout = QtWidgets.QGridLayout(self.dockWidgetContents)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.scrollArea = QtWidgets.QScrollArea(self.dockWidgetContents)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, -191, 238, 542))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox_3 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.formLayout_4 = QtWidgets.QFormLayout()
        self.formLayout_4.setObjectName("formLayout_4")
        self.label_10 = QtWidgets.QLabel(self.groupBox_3)
        self.label_10.setObjectName("label_10")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.freqDoubleSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox_3)
        self.freqDoubleSpinBox.setDecimals(3)
        self.freqDoubleSpinBox.setMinimum(0.1)
        self.freqDoubleSpinBox.setMaximum(100.0)
        self.freqDoubleSpinBox.setSingleStep(0.1)
        self.freqDoubleSpinBox.setProperty("value", 1.0)
        self.freqDoubleSpinBox.setObjectName("freqDoubleSpinBox")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.freqDoubleSpinBox)
        self.label_11 = QtWidgets.QLabel(self.groupBox_3)
        self.label_11.setObjectName("label_11")
        self.formLayout_4.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.timepercentDoubleSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox_3)
        self.timepercentDoubleSpinBox.setDecimals(3)
        self.timepercentDoubleSpinBox.setMinimum(0.001)
        self.timepercentDoubleSpinBox.setMaximum(50.0)
        self.timepercentDoubleSpinBox.setProperty("value", 2.0)
        self.timepercentDoubleSpinBox.setObjectName("timepercentDoubleSpinBox")
        self.formLayout_4.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.timepercentDoubleSpinBox)
        self.label_12 = QtWidgets.QLabel(self.groupBox_3)
        self.label_12.setObjectName("label_12")
        self.formLayout_4.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.stepsizeDoubleSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox_3)
        self.stepsizeDoubleSpinBox.setDecimals(1)
        self.stepsizeDoubleSpinBox.setMinimum(10.0)
        self.stepsizeDoubleSpinBox.setMaximum(10000.0)
        self.stepsizeDoubleSpinBox.setSingleStep(1.0)
        self.stepsizeDoubleSpinBox.setProperty("value", 10.0)
        self.stepsizeDoubleSpinBox.setObjectName("stepsizeDoubleSpinBox")
        self.formLayout_4.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.stepsizeDoubleSpinBox)
        self.label_4 = QtWidgets.QLabel(self.groupBox_3)
        self.label_4.setObjectName("label_4")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.tempDoubleSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox_3)
        self.tempDoubleSpinBox.setMinimum(200.0)
        self.tempDoubleSpinBox.setMaximum(350.0)
        self.tempDoubleSpinBox.setProperty("value", 293.15)
        self.tempDoubleSpinBox.setObjectName("tempDoubleSpinBox")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.tempDoubleSpinBox)
        self.label_13 = QtWidgets.QLabel(self.groupBox_3)
        self.label_13.setObjectName("label_13")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_13)
        self.pressDoubleSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox_3)
        self.pressDoubleSpinBox.setDecimals(1)
        self.pressDoubleSpinBox.setMinimum(10.0)
        self.pressDoubleSpinBox.setMaximum(1500.0)
        self.pressDoubleSpinBox.setProperty("value", 980.0)
        self.pressDoubleSpinBox.setObjectName("pressDoubleSpinBox")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.pressDoubleSpinBox)
        self.label_16 = QtWidgets.QLabel(self.groupBox_3)
        self.label_16.setObjectName("label_16")
        self.formLayout_4.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_16)
        self.versionComboBox = QtWidgets.QComboBox(self.groupBox_3)
        self.versionComboBox.setEnabled(False)
        self.versionComboBox.setObjectName("versionComboBox")
        self.versionComboBox.addItem("")
        self.versionComboBox.addItem("")
        self.versionComboBox.addItem("")
        self.formLayout_4.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.versionComboBox)
        self.label_6 = QtWidgets.QLabel(self.groupBox_3)
        self.label_6.setObjectName("label_6")
        self.formLayout_4.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.polarizationComboBox = QtWidgets.QComboBox(self.groupBox_3)
        self.polarizationComboBox.setObjectName("polarizationComboBox")
        self.polarizationComboBox.addItem("")
        self.polarizationComboBox.addItem("")
        self.formLayout_4.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.polarizationComboBox)
        self.gridLayout_4.addLayout(self.formLayout_4, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_3)
        self.groupBox_2 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setObjectName("label_3")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.txLonDoubleSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.txLonDoubleSpinBox.setDecimals(5)
        self.txLonDoubleSpinBox.setMinimum(-180.0)
        self.txLonDoubleSpinBox.setMaximum(180.0)
        self.txLonDoubleSpinBox.setSingleStep(0.05)
        self.txLonDoubleSpinBox.setProperty("value", 6.2)
        self.txLonDoubleSpinBox.setObjectName("txLonDoubleSpinBox")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.txLonDoubleSpinBox)
        self.label_14 = QtWidgets.QLabel(self.groupBox_2)
        self.label_14.setObjectName("label_14")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_14)
        self.txLatDoubleSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.txLatDoubleSpinBox.setDecimals(5)
        self.txLatDoubleSpinBox.setMinimum(-90.0)
        self.txLatDoubleSpinBox.setMaximum(90.0)
        self.txLatDoubleSpinBox.setSingleStep(0.05)
        self.txLatDoubleSpinBox.setProperty("value", 50.8)
        self.txLatDoubleSpinBox.setObjectName("txLatDoubleSpinBox")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.txLatDoubleSpinBox)
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setObjectName("label_5")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.txHeightDoubleSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.txHeightDoubleSpinBox.setDecimals(1)
        self.txHeightDoubleSpinBox.setMinimum(-500.0)
        self.txHeightDoubleSpinBox.setMaximum(1000000.0)
        self.txHeightDoubleSpinBox.setSingleStep(5.0)
        self.txHeightDoubleSpinBox.setProperty("value", 50.0)
        self.txHeightDoubleSpinBox.setObjectName("txHeightDoubleSpinBox")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.txHeightDoubleSpinBox)
        self.label = QtWidgets.QLabel(self.groupBox_2)
        self.label.setObjectName("label")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label)
        self.txClutterComboBox = QtWidgets.QComboBox(self.groupBox_2)
        self.txClutterComboBox.setObjectName("txClutterComboBox")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.txClutterComboBox)
        self.gridLayout_2.addLayout(self.formLayout_2, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.groupBox = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.formLayout_3 = QtWidgets.QFormLayout()
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setObjectName("label_7")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.rxLonDoubleSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.rxLonDoubleSpinBox.setDecimals(5)
        self.rxLonDoubleSpinBox.setMinimum(-180.0)
        self.rxLonDoubleSpinBox.setMaximum(180.0)
        self.rxLonDoubleSpinBox.setSingleStep(0.05)
        self.rxLonDoubleSpinBox.setProperty("value", 6.88361)
        self.rxLonDoubleSpinBox.setObjectName("rxLonDoubleSpinBox")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.rxLonDoubleSpinBox)
        self.label_15 = QtWidgets.QLabel(self.groupBox)
        self.label_15.setObjectName("label_15")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_15)
        self.rxLatDoubleSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.rxLatDoubleSpinBox.setDecimals(5)
        self.rxLatDoubleSpinBox.setMinimum(-90.0)
        self.rxLatDoubleSpinBox.setMaximum(90.0)
        self.rxLatDoubleSpinBox.setSingleStep(0.05)
        self.rxLatDoubleSpinBox.setProperty("value", 50.52483)
        self.rxLatDoubleSpinBox.setObjectName("rxLatDoubleSpinBox")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.rxLatDoubleSpinBox)
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        self.label_8.setObjectName("label_8")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.rxHeightDoubleSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.rxHeightDoubleSpinBox.setDecimals(1)
        self.rxHeightDoubleSpinBox.setMinimum(-500.0)
        self.rxHeightDoubleSpinBox.setMaximum(1000000.0)
        self.rxHeightDoubleSpinBox.setSingleStep(5.0)
        self.rxHeightDoubleSpinBox.setProperty("value", 10.0)
        self.rxHeightDoubleSpinBox.setObjectName("rxHeightDoubleSpinBox")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.rxHeightDoubleSpinBox)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.rxClutterComboBox = QtWidgets.QComboBox(self.groupBox)
        self.rxClutterComboBox.setObjectName("rxClutterComboBox")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.rxClutterComboBox)
        self.gridLayout_3.addLayout(self.formLayout_3, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem, 1, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupBox)
        self.gridLayout_5.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollArea, 0, 1, 1, 1)
        self.parametersDockWidget.setWidget(self.dockWidgetContents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.parametersDockWidget)
        self.pathpropDockWidget = QtWidgets.QDockWidget(MainWindow)
        self.pathpropDockWidget.setObjectName("pathpropDockWidget")
        self.dockWidgetContents_2 = QtWidgets.QWidget()
        self.dockWidgetContents_2.setObjectName("dockWidgetContents_2")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.dockWidgetContents_2)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.scrollArea_2 = QtWidgets.QScrollArea(self.dockWidgetContents_2)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, -22, 222, 132))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_2)
        self.gridLayout_7.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.pathprofPlotChooserComboBox = QtWidgets.QComboBox(self.scrollAreaWidgetContents_2)
        self.pathprofPlotChooserComboBox.setObjectName("pathprofPlotChooserComboBox")
        self.verticalLayout_2.addWidget(self.pathprofPlotChooserComboBox)
        self.pathprofIncludeHeightCheckBox = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_2)
        self.pathprofIncludeHeightCheckBox.setChecked(True)
        self.pathprofIncludeHeightCheckBox.setObjectName("pathprofIncludeHeightCheckBox")
        self.verticalLayout_2.addWidget(self.pathprofIncludeHeightCheckBox)
        self.pathprofAutoUpdateCheckBox = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_2)
        self.pathprofAutoUpdateCheckBox.setObjectName("pathprofAutoUpdateCheckBox")
        self.verticalLayout_2.addWidget(self.pathprofAutoUpdateCheckBox)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pathprofComputePushButton = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pathprofComputePushButton.sizePolicy().hasHeightForWidth())
        self.pathprofComputePushButton.setSizePolicy(sizePolicy)
        self.pathprofComputePushButton.setObjectName("pathprofComputePushButton")
        self.horizontalLayout_3.addWidget(self.pathprofComputePushButton)
        self.pathprofBusyIndicatorLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.pathprofBusyIndicatorLabel.setStyleSheet("QLabel {\n"
"    color : red;\n"
"}")
        self.pathprofBusyIndicatorLabel.setObjectName("pathprofBusyIndicatorLabel")
        self.horizontalLayout_3.addWidget(self.pathprofBusyIndicatorLabel)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.gridLayout_7.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.gridLayout_6.addWidget(self.scrollArea_2, 0, 0, 1, 1)
        self.pathpropDockWidget.setWidget(self.dockWidgetContents_2)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.pathpropDockWidget)
        self.mappingDockWidget = QtWidgets.QDockWidget(MainWindow)
        self.mappingDockWidget.setObjectName("mappingDockWidget")
        self.dockWidgetContents_3 = QtWidgets.QWidget()
        self.dockWidgetContents_3.setObjectName("dockWidgetContents_3")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.dockWidgetContents_3)
        self.gridLayout_11.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.scrollArea_3 = QtWidgets.QScrollArea(self.dockWidgetContents_3)
        self.scrollArea_3.setWidgetResizable(True)
        self.scrollArea_3.setObjectName("scrollArea_3")
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, -81, 222, 163))
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_3)
        self.gridLayout_12.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label_9 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label_9.setObjectName("label_9")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.label_17 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label_17.setObjectName("label_17")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_17)
        self.mapSizeLonDoubleSpinBox = QtWidgets.QDoubleSpinBox(self.scrollAreaWidgetContents_3)
        self.mapSizeLonDoubleSpinBox.setDecimals(3)
        self.mapSizeLonDoubleSpinBox.setMinimum(0.05)
        self.mapSizeLonDoubleSpinBox.setMaximum(5.0)
        self.mapSizeLonDoubleSpinBox.setSingleStep(0.05)
        self.mapSizeLonDoubleSpinBox.setProperty("value", 0.2)
        self.mapSizeLonDoubleSpinBox.setObjectName("mapSizeLonDoubleSpinBox")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.mapSizeLonDoubleSpinBox)
        self.mapSizeLatDoubleSpinBox = QtWidgets.QDoubleSpinBox(self.scrollAreaWidgetContents_3)
        self.mapSizeLatDoubleSpinBox.setDecimals(3)
        self.mapSizeLatDoubleSpinBox.setMinimum(0.05)
        self.mapSizeLatDoubleSpinBox.setMaximum(5.0)
        self.mapSizeLatDoubleSpinBox.setSingleStep(0.05)
        self.mapSizeLatDoubleSpinBox.setProperty("value", 0.2)
        self.mapSizeLatDoubleSpinBox.setObjectName("mapSizeLatDoubleSpinBox")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.mapSizeLatDoubleSpinBox)
        self.label_18 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label_18.setObjectName("label_18")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_18)
        self.mapResolutionDoubleSpinBox = QtWidgets.QDoubleSpinBox(self.scrollAreaWidgetContents_3)
        self.mapResolutionDoubleSpinBox.setDecimals(1)
        self.mapResolutionDoubleSpinBox.setMinimum(1.0)
        self.mapResolutionDoubleSpinBox.setMaximum(300.0)
        self.mapResolutionDoubleSpinBox.setProperty("value", 3.0)
        self.mapResolutionDoubleSpinBox.setObjectName("mapResolutionDoubleSpinBox")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.mapResolutionDoubleSpinBox)
        self.verticalLayout_3.addLayout(self.formLayout)
        self.mapPlotChooserComboBox = QtWidgets.QComboBox(self.scrollAreaWidgetContents_3)
        self.mapPlotChooserComboBox.setObjectName("mapPlotChooserComboBox")
        self.verticalLayout_3.addWidget(self.mapPlotChooserComboBox)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.mapComputePushButton = QtWidgets.QPushButton(self.scrollAreaWidgetContents_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mapComputePushButton.sizePolicy().hasHeightForWidth())
        self.mapComputePushButton.setSizePolicy(sizePolicy)
        self.mapComputePushButton.setObjectName("mapComputePushButton")
        self.horizontalLayout_4.addWidget(self.mapComputePushButton)
        self.mapBusyIndicatorLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.mapBusyIndicatorLabel.setStyleSheet("QLabel {\n"
"    color : red;\n"
"}")
        self.mapBusyIndicatorLabel.setObjectName("mapBusyIndicatorLabel")
        self.horizontalLayout_4.addWidget(self.mapBusyIndicatorLabel)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem2)
        self.gridLayout_12.addLayout(self.verticalLayout_3, 0, 0, 1, 1)
        self.scrollArea_3.setWidget(self.scrollAreaWidgetContents_3)
        self.gridLayout_11.addWidget(self.scrollArea_3, 0, 0, 1, 1)
        self.mappingDockWidget.setWidget(self.dockWidgetContents_3)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.mappingDockWidget)
        self.optionsDockWidget = QtWidgets.QDockWidget(MainWindow)
        self.optionsDockWidget.setObjectName("optionsDockWidget")
        self.dockWidgetContents_4 = QtWidgets.QWidget()
        self.dockWidgetContents_4.setObjectName("dockWidgetContents_4")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.dockWidgetContents_4)
        self.gridLayout_14.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.scrollArea_4 = QtWidgets.QScrollArea(self.dockWidgetContents_4)
        self.scrollArea_4.setWidgetResizable(True)
        self.scrollArea_4.setObjectName("scrollArea_4")
        self.scrollAreaWidgetContents_4 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_4.setGeometry(QtCore.QRect(0, 0, 238, 205))
        self.scrollAreaWidgetContents_4.setObjectName("scrollAreaWidgetContents_4")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_4)
        self.gridLayout_15.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.groupBox_4 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents_4)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_16 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_19 = QtWidgets.QLabel(self.groupBox_4)
        self.label_19.setObjectName("label_19")
        self.verticalLayout_5.addWidget(self.label_19)
        self.srtmPathPushButton = QtWidgets.QPushButton(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.srtmPathPushButton.sizePolicy().hasHeightForWidth())
        self.srtmPathPushButton.setSizePolicy(sizePolicy)
        self.srtmPathPushButton.setObjectName("srtmPathPushButton")
        self.verticalLayout_5.addWidget(self.srtmPathPushButton)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_21 = QtWidgets.QLabel(self.groupBox_4)
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_2.addWidget(self.label_21)
        self.srtmDownloadComboBox = QtWidgets.QComboBox(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.srtmDownloadComboBox.sizePolicy().hasHeightForWidth())
        self.srtmDownloadComboBox.setSizePolicy(sizePolicy)
        self.srtmDownloadComboBox.setObjectName("srtmDownloadComboBox")
        self.srtmDownloadComboBox.addItem("")
        self.srtmDownloadComboBox.addItem("")
        self.srtmDownloadComboBox.addItem("")
        self.horizontalLayout_2.addWidget(self.srtmDownloadComboBox)
        self.verticalLayout_5.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_20 = QtWidgets.QLabel(self.groupBox_4)
        self.label_20.setObjectName("label_20")
        self.horizontalLayout.addWidget(self.label_20)
        self.srtmServerComboBox = QtWidgets.QComboBox(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.srtmServerComboBox.sizePolicy().hasHeightForWidth())
        self.srtmServerComboBox.setSizePolicy(sizePolicy)
        self.srtmServerComboBox.setObjectName("srtmServerComboBox")
        self.srtmServerComboBox.addItem("")
        self.srtmServerComboBox.addItem("")
        self.srtmServerComboBox.addItem("")
        self.horizontalLayout.addWidget(self.srtmServerComboBox)
        self.verticalLayout_5.addLayout(self.horizontalLayout)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem3)
        self.gridLayout_16.addLayout(self.verticalLayout_5, 0, 0, 1, 1)
        self.gridLayout_15.addWidget(self.groupBox_4, 0, 0, 1, 1)
        self.scrollArea_4.setWidget(self.scrollAreaWidgetContents_4)
        self.gridLayout_14.addWidget(self.scrollArea_4, 0, 0, 1, 1)
        self.optionsDockWidget.setWidget(self.dockWidgetContents_4)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.optionsDockWidget)
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.menuFile.addAction(self.actionQuit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.versionComboBox.setCurrentIndex(1)
        self.srtmServerComboBox.setCurrentIndex(2)
        self.actionQuit.triggered.connect(MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "pycraf GUI"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.geometryTab), _translate("MainWindow", "Geometry"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.statisticsTab), _translate("MainWindow", "Statistics"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.pathprofileTab), _translate("MainWindow", "Path profile"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.mapTab), _translate("MainWindow", "Map"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.parametersDockWidget.setWindowTitle(_translate("MainWindow", "General parameters"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Conditions"))
        self.label_10.setText(_translate("MainWindow", "Frequency"))
        self.freqDoubleSpinBox.setSuffix(_translate("MainWindow", " GHz"))
        self.label_11.setText(_translate("MainWindow", "Time percent"))
        self.timepercentDoubleSpinBox.setSuffix(_translate("MainWindow", " %"))
        self.label_12.setText(_translate("MainWindow", "Step size"))
        self.stepsizeDoubleSpinBox.setSuffix(_translate("MainWindow", " m"))
        self.label_4.setText(_translate("MainWindow", "Temperature"))
        self.tempDoubleSpinBox.setSuffix(_translate("MainWindow", " K"))
        self.label_13.setText(_translate("MainWindow", "Pressure"))
        self.pressDoubleSpinBox.setSuffix(_translate("MainWindow", " hPa"))
        self.label_16.setText(_translate("MainWindow", "Version"))
        self.versionComboBox.setItemText(0, _translate("MainWindow", "14"))
        self.versionComboBox.setItemText(1, _translate("MainWindow", "16"))
        self.versionComboBox.setItemText(2, _translate("MainWindow", "17"))
        self.label_6.setText(_translate("MainWindow", "Polarization"))
        self.polarizationComboBox.setItemText(0, _translate("MainWindow", "Horizontal"))
        self.polarizationComboBox.setItemText(1, _translate("MainWindow", "Vertical"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Transmitter"))
        self.label_3.setText(_translate("MainWindow", "Longitude"))
        self.txLonDoubleSpinBox.setSuffix(_translate("MainWindow", " deg"))
        self.label_14.setText(_translate("MainWindow", "Latitude"))
        self.txLatDoubleSpinBox.setSuffix(_translate("MainWindow", " deg"))
        self.label_5.setText(_translate("MainWindow", "Height"))
        self.txHeightDoubleSpinBox.setSuffix(_translate("MainWindow", " m"))
        self.label.setText(_translate("MainWindow", "Clutter"))
        self.groupBox.setTitle(_translate("MainWindow", "Receiver"))
        self.label_7.setText(_translate("MainWindow", "Longitude"))
        self.rxLonDoubleSpinBox.setSuffix(_translate("MainWindow", " deg"))
        self.label_15.setText(_translate("MainWindow", "Latitude"))
        self.rxLatDoubleSpinBox.setSuffix(_translate("MainWindow", " deg"))
        self.label_8.setText(_translate("MainWindow", "Height"))
        self.rxHeightDoubleSpinBox.setSuffix(_translate("MainWindow", " m"))
        self.label_2.setText(_translate("MainWindow", "Clutter"))
        self.pathpropDockWidget.setWindowTitle(_translate("MainWindow", "Path profile"))
        self.pathprofIncludeHeightCheckBox.setText(_translate("MainWindow", "Include height profile"))
        self.pathprofAutoUpdateCheckBox.setText(_translate("MainWindow", "Auto update"))
        self.pathprofComputePushButton.setText(_translate("MainWindow", "Compute"))
        self.pathprofBusyIndicatorLabel.setText(_translate("MainWindow", "Busy"))
        self.mappingDockWidget.setWindowTitle(_translate("MainWindow", "Mapping"))
        self.label_9.setText(_translate("MainWindow", "Size longitude"))
        self.label_17.setText(_translate("MainWindow", "Size latitude"))
        self.mapSizeLonDoubleSpinBox.setSuffix(_translate("MainWindow", " deg"))
        self.mapSizeLatDoubleSpinBox.setSuffix(_translate("MainWindow", " deg"))
        self.label_18.setText(_translate("MainWindow", "Resolution"))
        self.mapResolutionDoubleSpinBox.setSuffix(_translate("MainWindow", " arcsec"))
        self.mapComputePushButton.setText(_translate("MainWindow", "Compute"))
        self.mapBusyIndicatorLabel.setText(_translate("MainWindow", "Busy"))
        self.optionsDockWidget.setWindowTitle(_translate("MainWindow", "Options"))
        self.groupBox_4.setTitle(_translate("MainWindow", "SRTM configuration"))
        self.label_19.setText(_translate("MainWindow", "Tile path:"))
        self.srtmPathPushButton.setText(_translate("MainWindow", "PushButton"))
        self.label_21.setText(_translate("MainWindow", "Download"))
        self.srtmDownloadComboBox.setItemText(0, _translate("MainWindow", "Never"))
        self.srtmDownloadComboBox.setItemText(1, _translate("MainWindow", "Missing"))
        self.srtmDownloadComboBox.setItemText(2, _translate("MainWindow", "Always"))
        self.label_20.setText(_translate("MainWindow", "Server"))
        self.srtmServerComboBox.setItemText(0, _translate("MainWindow", "NASA v1.0"))
        self.srtmServerComboBox.setItemText(1, _translate("MainWindow", "NASA v2.1"))
        self.srtmServerComboBox.setItemText(2, _translate("MainWindow", "Viewfinder panoramas"))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))

from pycraf.gui.resources import resources_rc
